#!/bin/bash

RED='\033[0;31m'
# used for color with ${RED}
NC='\033[0m'
# No Color

cp ~/RoninDojo/Scripts/.dialogrc ~/.dialogrc
# config file for dialog color

rm -f ~/ronin-update.sh
# removes ronin-update script if found, will not output error if not found which keeps things clean

HEIGHT=22
WIDTH=76
CHOICE_HEIGHT=16
TITLE="RoninDojo"
MENU="Choose one of the following options:"

OPTIONS=(1 "Dojo Menu"
         2 "Whirlpool Menu"
         3 "Electrs Menu"
         4 "Firewall Menu"
         5 "System Menu"
         6 "System Setup & Installations")

CHOICE=$(dialog --clear \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            bash ~/RoninDojo/Scripts/Menu/menu-dojo.sh
            # runs dojo management menu script
            ;;
        2)
            bash ~/RoninDojo/Scripts/Menu/menu-whirlpool.sh
            # runs the whirlpool menu script
            ;;
        3)
            bash ~/RoninDojo/Scripts/Menu/menu-electrs.sh
            # runs electrs menu script
            ;;
        4)
            bash ~/RoninDojo/Scripts/Menu/menu-firewall.sh
            # runs firewall menu script
            ;;
        5)
            bash ~/RoninDojo/Scripts/Menu/menu-system.sh
            # runs system menu script
            ;;
        6)
            bash ~/RoninDojo/Scripts/Menu/menu-install.sh
	    # runs installs menu
            ;;
esac
