#!/bin/bash

. ~/RoninDojo/Scripts/defaults.sh

cp ~/RoninDojo/Scripts/.dialogrc ~/.dialogrc
# config file for dialog color

OPTIONS=(1 "Dojo Menu"
         2 "Whirlpool Menu"
         3 "Electrs Menu"
         4 "Firewall Menu"
         5 "System Menu"
         6 "System Setup & Installations"
         7 "Exit RoninDojo")

CHOICE=$(dialog --clear \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            bash ~/RoninDojo/Scripts/Menu/menu-dojo.sh
            # runs dojo management menu script
            ;;
        2)
            bash ~/RoninDojo/Scripts/Menu/menu-whirlpool.sh
            # runs the whirlpool menu script
            ;;
        3)
            bash ~/RoninDojo/Scripts/Menu/menu-electrs.sh
            # runs electrs menu script
            ;;
        4)
            bash ~/RoninDojo/Scripts/Menu/menu-firewall.sh
            # runs firewall menu script
            ;;
        5)
            bash ~/RoninDojo/Scripts/Menu/menu-system.sh
            # runs system menu script
            ;;
        6)
            bash ~/RoninDojo/Scripts/Menu/menu-install.sh
	    # runs installs menu
            ;;
    	255)
            clear
	        echo -e "${RED}RoninDojo Exiting...${NC}" >&2
	        sleep 2
	        exit 1
        # exits Ronin
	        ;;
esac
