#!/bin/bash
# shellcheck source=/dev/null

. "$HOME"/RoninDojo/Scripts/defaults.sh
. "$HOME"/RoninDojo/Scripts/functions.sh

# Run system checks
_main

test -f "$HOME"/.dialogrc || cp "$HOME"/RoninDojo/Scripts/.dialogrc "$HOME"/.dialogrc
# config file for dialog color

OPTIONS=(1 "Dojo"
         2 "UI Backend"
         3 "Credentials"
         4 "Applications"
         5 "Samourai Toolkit"
         6 "System"
         7 "Exit RoninDojo")

CHOICE=$(dialog --clear \
                --title "$TITLE" \
                --menu "$MENU" \
                "$HEIGHT" "$WIDTH" "$CHOICE_HEIGHT" \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
    1)
        bash "$HOME"/RoninDojo/Scripts/Menu/menu-dojo.sh
        # runs dojo management menu script
        ;;
    2)
        bash "$HOME"/RoninDojo/Scripts/Menu/menu-ronin-ui-backend.sh
        # runs Ronin UI Backend menu script
        ;;
    3)
        bash "$HOME"/RoninDojo/Scripts/Menu/menu-credentials.sh
        # runs credentials menu script
        ;;
    4)
        bash "$HOME"/RoninDojo/Scripts/Menu/menu-applications.sh
        # runs extras menu script
        ;;
    5)
        bash "$HOME"/RoninDojo/Scripts/Menu/menu-samourai-toolkit.sh
        # runs extras menu script
        ;;
    6)
        bash "$HOME"/RoninDojo/Scripts/Menu/menu-system.sh
        # runs system menu script
        ;;
    255|9)
        _sleep 5 --msg "RoninDojo Exiting in"
        exit 0
        # exits Ronin
        ;;
esac
