#!/bin/bash -x

RED=$(tput setaf 1)
NC=$(tput sgr0)

while true; do
    read -rp "Y/N" yn
    case $yn in
        [Yy])
            echo "ds"
            break
            ;;
        *)
            echo "wrong"
            continue
            ;;
    esac
done